- name: Build, Push Docker Image and Deploy to Kubernetes
  hosts: localhost
  connection: local

  vars:
    image_name: my-compte-service
    image_tag: v1
    dockerfile_path: './'

    # Identifiants Docker Hub
    docker_registry_username: afwacherni123
    docker_registry_password: 123456789

    # InterprÃ©teur Python dans ton environnement Ansible
    ansible_python_interpreter: /home/afwa/ansible-env/bin/python

    # ðŸ”§ CLÃ‰ IMPORTANTE : forcer Ansible Ã  utiliser le socket Docker de WSL
    docker_host: unix:///var/run/docker.sock

    namespace: jenkins

  tasks:

    - name: Log in to Docker Hub
      community.general.docker_login:
        username: "{{ docker_registry_username }}"
        password: "{{ docker_registry_password }}"
        reauthorize: yes
      vars:
        docker_host: "{{ docker_host }}"   # <--- AjoutÃ© ici

    - name: Build Docker image
      community.general.docker_image:
        build:
          path: "{{ dockerfile_path }}"
        name: "{{ docker_registry_username }}/{{ image_name }}"
        tag: "{{ image_tag }}"
        source: build
        state: present
      vars:
        docker_host: "{{ docker_host }}"   # <--- AjoutÃ© ici

    - name: Push Docker image to Docker Hub
      community.general.docker_image:
        name: "{{ docker_registry_username }}/{{ image_name }}"
        tag: "{{ image_tag }}"
        push: yes
        source: local
      vars:
        docker_host: "{{ docker_host }}"   # <--- AjoutÃ© ici

    - name: Verify Docker image pull (optional, for verification)
      community.general.docker_image:
        name: "{{ docker_registry_username }}/{{ image_name }}"
        tag: "{{ image_tag }}"
        source: pull
      vars:
        docker_host: "{{ docker_host }}"   # <--- AjoutÃ© ici

    - name: Apply Kubernetes Deployment
      kubernetes.core.k8s:
        state: present
        namespace: "{{ namespace }}"
        src: my-deployment.yaml

    - name: Apply Kubernetes Service
      kubernetes.core.k8s:
        state: present
        namespace: "{{ namespace }}"
        src: service.yaml
