- name: Build, Push Docker Image and Deploy to Kubernetes
  hosts: localhost
  connection: local

  vars:
    image_name: my-compte-service
    image_tag: v1
    dockerfile_path: './'
    # ATTENTION: Changez ces valeurs pour vos identifiants réels
    docker_registry_username: afwacherni123 
    docker_registry_password: 123456789
    
    # POINT DE CORRECTION MAJEUR : 
    # Pointe vers l'interpréteur Python dans le nouvel environnement virtuel (venv)
    ansible_python_interpreter: /home/afwa/ansible-env/bin/python 
    
    namespace: jenkins

  tasks:
    # Tâche 'pip' (Ensure required Python packages are installed) RETIRÉE.
    # Les packages (kubernetes, openshift, etc.) doivent être installés manuellement
    # dans le venv avant l'exécution du pipeline.

    - name: Log in to Docker Hub
      community.general.docker_login:
        username: "{{ docker_registry_username }}"
        password: "{{ docker_registry_password }}"
        reauthorize: yes

    - name: Build Docker image
      community.general.docker_image:
        build:
          path: "{{ dockerfile_path }}"
        name: "{{ docker_registry_username }}/{{ image_name }}"
        tag: "{{ image_tag }}"
        source: build
        state: present

    - name: Push Docker image to Docker Hub
      community.general.docker_image:
        name: "{{ docker_registry_username }}/{{ image_name }}"
        tag: "{{ image_tag }}"
        push: yes
        source: local

    - name: Verify Docker image pull (optional, for verification)
      community.general.docker_image:
        name: "{{ docker_registry_username }}/{{ image_name }}"
        tag: "{{ image_tag }}"
        source: pull

    - name: Apply Kubernetes Deployment
      kubernetes.core.k8s:
        state: present
        namespace: "{{ namespace }}"
        src: my-deployment.yaml

    - name: Apply Kubernetes Service
      kubernetes.core.k8s:
        state: present
        namespace: "{{ namespace }}"
        src: service.yaml
