---
- name: Build and Deploy Docker Image to Kubernetes
  hosts: localhost  # or your build/deployment server
  connection: local

  vars:
    image_name: my-compte-service
    image_tag: v1
    dockerfile_path: ./
    docker_registry_username: "afwacherni123"
    docker_registry_password: "123456789"

  tasks:

    - name: Log in to Docker Hub
      community.general.docker_login:
        username: "{{ docker_registry_username }}"
        password: "{{ docker_registry_password }}"
        reauthorize: yes  # Re-authenticate even if credentials exist

    - name: Build Docker image
      community.general.docker_image:
        build:
          path: "{{ dockerfile_path }}"
        name: "{{ docker_registry_username }}/{{ image_name }}"
        tag: "{{ image_tag }}"
        source: build
        state: present

    - name: Push Docker image to Docker Hub
      community.general.docker_image:
        name: "{{ docker_registry_username }}/{{ image_name }}"
        tag: "{{ image_tag }}"
        push: yes
        source: local

    - name: Pull Docker image (optional, for verification or on target nodes)
      community.general.docker_image:
        name: "{{ docker_registry_username }}/{{ image_name }}"
        tag: "{{ image_tag }}"
        source: pull

    - name: Apply Kubernetes Deployment
      kubernetes.core.k8s:
        state: present
        namespace: jenkins
        src: my-deployment.yaml
        kubeconfig: config  # Path to your kubeconfig file

    - name: Apply Kubernetes Service
      kubernetes.core.k8s:
        state: present
        namespace: jenkins
        src: service.yaml
        kubeconfig: config
