apiVersion: v1
kind: Service
metadata:
  name: my-compte-service
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/actuator/prometheus"
    prometheus.io/port: "8082"
spec:
  type: NodePort
  selector:
    app: compte-service
  ports:
    - port: 8082
      name: http
      targetPort: 8082
      #nodePort: 30007
      protocol: TCP
